sudo: false
language: java
services:
  - docker
cache:
  directories:
  - "$HOME/.cache"

deploy:
  before_install:
    - docker login -u="$DOCKER_USER" -p="$DOCKER_PWD"
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true

script:
  - mvn clean install -Pdocker
