version: "3"

services:
  identity:
    image: g-suite-identity-sync:0.1.0-SNAPSHOT
    ports:
      - 8443:8443
      - 8101:8101
    environment:
      - SLAPD_BIND_DN=cn=admin,dc=example,dc=org
      - SLAPD_BASE_DN=dc=example,dc=org
      - SLAPD_PASSWORD=changeme
      - GSUITE_DOMAIN=example.org
      - GSUITE_SERVICE_ACCOUNT_EMAIL=gsuite-services-client@******.gserviceaccount.com
      - GSUITE_SERVICE_ACCOUNT_SUBJECT=some-admin@example.org
      - GSUITE_CLIENT_ID=*******.apps.googleusercontent.com
      - GSUITE_CLIENT_SECRET=******
    depends_on:
      - ldap
    volumes:
      - account-config:/opt/karaf/etc

  ldap:
    image: dinkel/openldap
    ports:
      - "389:389"
    environment:
      - SLAPD_PASSWORD=changeme
      - SLAPD_CONFIG_PASSWORD=changeme
      - SLAPD_DOMAIN=example.org
      - SLAPD_ORGANIZATION=Example ltd.
      - SLAPD_ADDITIONAL_SCHEMAS=ppolicy
      - SLAPD_ADDITIONAL_MODULES=ppolicy,memberof
    volumes:
      - ldap-config:/etc/ldap
      - ldap-data:/var/lib/ldap

volumes:
  account-config:
  ldap-config:
  ldap-data:
