version: "3"

services:
  account:
    image: docker.xit.camp/account-manager
    hostname: account
    depends_on:
      - ldap
    volumes:
      - /data/home/hlavki/develop/xit/_config/camp.xit.identity.cfg:/opt/karaf/etc/camp.xit.identity.cfg
      - /data/home/hlavki/develop/xit/_config/keystore:/opt/karaf/etc/keystore

  httpd:
    image: httpd
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/home/hlavki/develop/xit/docker-data/httpd/conf:/usr/local/apache2/conf
      - /data/home/hlavki/develop/xit/docker-data/httpd/htdocs:/usr/local/apache2/htdocs

  ldap:
    image: dinkel/openldap
    hostname: ldap
    ports:
      - "389:389"
    environment:
      #- SLAPD_PASSWORD=
      #- SLAPD_CONFIG_PASSWORD=
      - SLAPD_DOMAIN=xit.camp
      - SLAPD_ORGANIZATION=xIT
      - SLAPD_ADDITIONAL_SCHEMAS=ppolicy
      - SLAPD_ADDITIONAL_MODULES=ppolicy,memberof
    volumes:
      - /data/home/hlavki/develop/xit/docker-data/ldap/config:/etc/ldap
      - /data/home/hlavki/develop/xit/docker-data/ldap/data:/var/lib/ldap
